version: 0.1

environment_variables:
  plaintext:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
      - apt-get install -y curl
      - mkdir -p ~/k6-bin
      - |
        curl -O -L https://github.com/loadimpact/k6/releases/download/v0.17.1/k6-v0.17.1-linux64.tar.gz;
        tar -xvzf k6-v0.17.1-linux64.tar.gz;
        mv k6-v0.17.1-linux64/k6 ~/k6-bin/k6;
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - ~/k6-bin/k6 run -q -o cloud loadtests/main.js      
  post_build:
    commands:
      - echo Build completed on `date`
